#!/bin/sh -

# Trash Script
# Moves files to trash either through a trash command aliased to this script, adding the
# script's path to the PATH, or adding an alias for rm to use this script instead (or both).

if [ $# -eq 0 ]; then
    echo
    echo "Error: No file(s) specified."
    echo "USAGE: trash file1 [ file2 [ ... ] ]"
    echo
    exit 1
fi

if [ ! -d .trash ]; then
    mkdir .trash

    if [ $? -ne 0 ]; then
        echo "Error: Could not create directory ~/.trash."
        exit 1
    fi
fi

TIMESTAMP=`date +"%Y%m%d%H%M%S"`

mkdir .trash/${TIMESTAMP}

if [ $? -ne 0 ]; then
    echo "Error: Could not create directory ~/.trash/${TIMESTAMP}."
    exit 1
fi

mv -i -v --strip-trailing-slashes -t .trash/${TIMESTAMP} "$@"

if [ $? -ne 0 ]; then
    echo "Error: Could not move files successfully; see output for details."
    exit 1
fi

exit 0

